apiVersion: che.eclipse.org/v1alpha1
kind: KubernetesImagePuller
metadata:
  name: fedaura-image-puller
  namespace: openshift-operators
spec:
  daemonsetName: fedaura-image-puller
  images: "fedaura-codeserver=quay.io/rh-aiservices-bu/fedaura-codeserver:1.0"
  cachingIntervalHours: "1"
  cachingMemoryRequest: "10Mi"
  cachingMemoryLimit: "20Mi"
