apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshell-portforward
rules:
- apiGroups: [""]
  resources: ["pods", "pods/portforward"]
  verbs: ["get", "list", "create"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workbench-openshell-portforward
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshell-portforward
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:NAMESPACE_PLACEHOLDER
