apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: openshell-gw
  namespace: wksp-user1
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: openshell
  port:
    targetPort: 8080
