apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: openshell-gw
  namespace: wskp-user1
  annotations:
    haproxy.router.openshift.io/enable-h2c: "true"
spec:
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  to:
    kind: Service
    name: openshell
  port:
    targetPort: grpc
