---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - catalog-source-cleanup-rbac.yaml
  - catalog-source-update-job.yaml
  - vllm-cpu-serving-runtime.yaml
  - llmdsvcconfig.yaml
  - llmroutingconfig.yaml
  - llmschedulingpolicy.yaml
