---
apiVersion: v1
kind: Secret
metadata:
  name: automl
  namespace: wskp-user1
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  annotations:
    opendatahub.io/connection-type: s3
    opendatahub.io/connection-type-protocol: s3
    opendatahub.io/connection-type-ref: s3
    openshift.io/display-name: automl
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: IJrixDGbADAkgey5
  AWS_DEFAULT_REGION: wonderland
  AWS_S3_ENDPOINT: http://minio-service.wskp-user1.svc.cluster.local:9000
  AWS_S3_BUCKET: automl
