---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - qwen3-06b-servingruntime.yaml
  - qwen3-06b-inferenceservice.yaml
  - tinyllama-servingruntime.yaml
  - tinyllama-inferenceservice.yaml
