---
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaasTenantConfig
metadata:
  name: default-tenant
  namespace: models-as-a-service
  labels:
    ai-gateway.opendatahub.io/tenant: models-as-a-service
    maas.opendatahub.io/tenant-name: models-as-a-service
    maas.opendatahub.io/tenant-namespace: models-as-a-service
spec: {}
